spring.application.name=mvpsi
spring.datasource.url=jdbc:mysql://localhost:3306/mvpsi?serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
logging.level.org.springframework.security=DEBUG